//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RentCarEntities : DbContext
    {
        public RentCarEntities()
            : base("name=RentCarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADO { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<MODELO> MODELO { get; set; }
        public virtual DbSet<RENTADEVOLUCION> RENTADEVOLUCION { get; set; }
        public virtual DbSet<TIPOCOMBUSTIBLE> TIPOCOMBUSTIBLE { get; set; }
        public virtual DbSet<TIPOVEHICULO> TIPOVEHICULO { get; set; }
        public virtual DbSet<Vehiculo> Vehiculo { get; set; }
        public virtual DbSet<INSPECCION> INSPECCION { get; set; }
    
        public virtual ObjectResult<FILTERBYDATE_Result> FILTERBYDATE(Nullable<System.DateTime> dESDE, Nullable<System.DateTime> hASTA)
        {
            var dESDEParameter = dESDE.HasValue ?
                new ObjectParameter("DESDE", dESDE) :
                new ObjectParameter("DESDE", typeof(System.DateTime));
    
            var hASTAParameter = hASTA.HasValue ?
                new ObjectParameter("HASTA", hASTA) :
                new ObjectParameter("HASTA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FILTERBYDATE_Result>("FILTERBYDATE", dESDEParameter, hASTAParameter);
        }
    }
}
