//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSPECCION
    {
        public int IdInspeccion { get; set; }
        public int IdVehiculo { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public string Ralladuras { get; set; }
        public string CantidadCombustible { get; set; }
        public string GomaRepuesto { get; set; }
        public string Gato { get; set; }
        public string RoturaCristal { get; set; }
        public string EstadoNeumatico1 { get; set; }
        public string EstadoNeumatico2 { get; set; }
        public string EstadoNeumatico3 { get; set; }
        public string EstadoNeumatico4 { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
