//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTADEVOLUCION
    {
        public int IdRentaDevolucion { get; set; }
        public int IdEmpleado { get; set; }
        public int IdCliente { get; set; }
        public int IdVehiculo { get; set; }
        public System.DateTime FechaRenta { get; set; }
        public decimal MontoDia { get; set; }
        public string CantidadDias { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaDevolucon { get; set; }
        public Nullable<decimal> MontoAtraso { get; set; }
        public string Comentarios { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
